import type { Lang } from "./i18n";
const en = {
  talk: "Talk", work: "Work", aqua: "1inch Aqua", navigation: "Companion activities", switcher: "Your companions",
  title: "A little help, from your companion.", subtitle: "World ID · ENS · 1inch Aqua + SwapVM",
  environment: "Sepolia · test tokens", approvals: "Approvals: World ID for Agents (Sandbox · mocked identity)",
  next: "Your approval is needed", approvalHint: "Review the action below. Nothing here runs without your approval.", invalid: "This action could not be read. Refresh before approving.",
  request: "Request", deliver: "Delivery", review: "Review", reward: "Reward", workTitle: "One request. A real result.", workHint: "Review the delivery, then approve the test-token reward separately.",
  workerHint: "Accept a request, deliver the result, then wait for review and reward.", noIncoming: "No requests yet. Other companions can ask you for a small job.",
  noWork: "No jobs yet. Start a small request from Talk.", incoming: "Received jobs", outgoing: "Jobs you requested", finished: "Reward paid", history: "Completed activity", result: "View delivery & receipt", receipt: "Payment receipt", refresh: "Refresh status", noPeers: "No work companion is available yet.",
  aquaTitle: "A test exchange, step by step.", aquaHint: "Tokens stay in the companion wallet at setup. A swap sends and receives tokens.", setup: "Prepare", approve: "Start", swap: "Swap", stop: "Stop", stopped: "Stopped", ready: "Ready to start", active: "Active", wallet: "Wallet now", mechanics: "How this demo works", pastStrategies: "Stopped strategies", strategy: "Strategy", deadline: "Expires", noAqua: "Aqua is not configured for this environment.",
  explain: "Say hello", explainPrompt: "Introduce yourself in one short sentence, in English. Do not create a transaction or job.", latest: "Latest reply", details: "Evidence & profile", counts: "These counts describe jobs this companion delivered. Jobs you requested are shown in Work.", technical: "Technical details", sent: "Submitted", failed: "Not completed", retry: "Refresh",
};
type Copy = typeof en;
export const DEMO_COPY: Record<Lang, Copy> = {
 en,
 ja: { talk:"会話",work:"仕事",aqua:"1inch Aqua",navigation:"相棒の操作",switcher:"あなたの相棒",title:"お願いを、相棒と一緒に。",subtitle:"World ID · ENS · 1inch Aqua + SwapVM",environment:"Sepolia・テストトークン",approvals:"承認：World ID for Agents（Sandbox・模擬ID）",next:"あなたの承認を待っています",approvalHint:"内容を確認して承認します。承認前には実行されません。",invalid:"操作内容を読み取れません。更新してから確認してください。",request:"依頼",deliver:"納品",review:"検収",reward:"報酬",workTitle:"頼む。届く。確かめる。",workHint:"届いた内容を検収してから、テスト報酬を別途承認します。",workerHint:"依頼を受けて納品します。検収と報酬の承認は依頼主が行います。",noIncoming:"まだ依頼はありません。ほかの相棒から仕事が届くのを待っています。",noWork:"まだ仕事はありません。「会話」から小さな仕事を頼めます。",incoming:"受けた仕事",outgoing:"頼んだ仕事",finished:"報酬支払い済み",history:"完了した記録",result:"納品と支払いを見る",receipt:"支払いの証拠",refresh:"状態を更新",noPeers:"依頼できる仕事用の相棒がいません。",aquaTitle:"テスト交換を、一歩ずつ。",aquaHint:"設定時は相棒のウォレットに残り、交換時にトークンを送受信します。",setup:"準備",approve:"開始",swap:"交換",stop:"停止",stopped:"停止済み",ready:"開始待ち",active:"交換受付中",wallet:"現在のウォレット",mechanics:"このデモの仕組み",pastStrategies:"停止した戦略",strategy:"戦略",deadline:"期限",noAqua:"この環境ではAquaが設定されていません。",explain:"自己紹介して",explainPrompt:"日本語で一言、自己紹介して。送金や仕事の依頼は作らないで。",latest:"最新の返事",details:"証拠とプロフィール",counts:"ここは、この相棒が納品した仕事の件数です。依頼した仕事は「仕事」で確認できます。",technical:"技術詳細",sent:"送信済み",failed:"未完了",retry:"更新" },
 zh: { talk:"对话",work:"工作",aqua:"1inch Aqua",navigation:"搭档活动",switcher:"你的搭档",title:"和搭档一起完成心愿。",subtitle:en.subtitle,environment:"Sepolia · 测试代币",approvals:"批准：World ID for Agents（Sandbox·模拟ID）",next:"等待你的批准",approvalHint:"确认操作内容，批准后才会执行。",invalid:"无法读取操作，请刷新后确认。",request:"委托",deliver:"交付",review:"验收",reward:"奖励",workTitle:"委托、交付、确认。",workHint:"验收交付内容，再单独批准测试奖励。",workerHint:"接受任务并交付结果，然后等待委托人验收和批准奖励。",noIncoming:"暂无收到的任务。其他搭档可以委托小任务。",noWork:"暂无任务。可从对话开始委托。",incoming:"收到的任务",outgoing:"委托的任务",finished:"奖励已支付",history:"已完成记录",result:"查看交付与凭证",receipt:"支付凭证",refresh:"刷新状态",noPeers:"暂无可委托的工作搭档。",aquaTitle:"逐步体验测试交换。",aquaHint:"设置时代币留在搭档钱包，交换时才收发代币。",setup:"准备",approve:"开始",swap:"交换",stop:"停止",stopped:"已停止",ready:"等待开始",active:"接受交换",wallet:"当前钱包",mechanics:"演示原理",pastStrategies:"已停止策略",strategy:"策略",deadline:"到期",noAqua:"此环境尚未配置Aqua。",explain:"自我介绍",explainPrompt:"请用中文一句话介绍自己，不要创建交易或工作。",latest:"最新回复",details:"凭证与资料",counts:"这些数字是该搭档交付的任务。委托的任务显示在工作中。",technical:"技术详情",sent:"已提交",failed:"未完成",retry:"刷新" },
 ko: { talk:"대화",work:"작업",aqua:"1inch Aqua",navigation:"파트너 활동",switcher:"나의 파트너",title:"부탁을 파트너와 함께.",subtitle:en.subtitle,environment:"Sepolia · 테스트 토큰",approvals:"승인: World ID for Agents(Sandbox·모의 ID)",next:"승인을 기다리고 있어요",approvalHint:"내용을 확인해 주세요. 승인 전에는 실행되지 않아요.",invalid:"작업을 읽을 수 없어요. 새로고침 후 확인해 주세요.",request:"의뢰",deliver:"납품",review:"검수",reward:"보상",workTitle:"의뢰하고, 받고, 확인해요.",workHint:"납품을 검수한 후 테스트 보상을 별도로 승인해요.",workerHint:"의뢰를 받아 납품해요. 검수와 보상 승인은 의뢰인이 해요.",noIncoming:"아직 의뢰가 없어요. 다른 파트너가 작업을 맡길 수 있어요.",noWork:"아직 작업이 없어요. 대화에서 작은 작업을 의뢰해 보세요.",incoming:"받은 작업",outgoing:"의뢰한 작업",finished:"보상 지급 완료",history:"완료된 기록",result:"납품 및 결제 보기",receipt:"결제 증명",refresh:"상태 새로고침",noPeers:"의뢰할 작업 파트너가 없어요.",aquaTitle:"테스트 교환을 한 단계씩.",aquaHint:"설정 시 토큰은 파트너 지갑에 남고 교환 시 주고받아요.",setup:"준비",approve:"시작",swap:"교환",stop:"중지",stopped:"중지됨",ready:"시작 대기",active:"교환 가능",wallet:"현재 지갑",mechanics:"데모 원리",pastStrategies:"중지된 전략",strategy:"전략",deadline:"만료",noAqua:"이 환경에 Aqua가 설정되지 않았어요.",explain:"자기소개",explainPrompt:"한국어 한 문장으로 자기소개해 줘. 거래나 작업을 만들지 마.",latest:"최근 답변",details:"증명과 프로필",counts:"이 수치는 파트너가 납품한 작업이에요. 의뢰한 작업은 작업에서 확인하세요.",technical:"기술 정보",sent:"제출됨",failed:"미완료",retry:"새로고침" }
};
